name: lorenzsw
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytest
  - scienceplots
  - pip
  - pip:
      - loguru
      - pytest-cov
      - mkdocs
      - pydmd
      - nolds
      - requests
